### ISSUE TITLE
moveByRotorSpeed example call and build

### ISSUE THREAD

**Issue by juanmed** [zbenic/MultirotorRL#1]
Hello! 

I was looking into your moveByRotorSpeed implementation. I was wondering if you included any example call of this function in your MultirotorRL repository. I looked into both PythonClient and HelloDrone folders but it did not seem to be any example call there. 

I know this is a bit old repository but if you still remember, would you mind letting me know how to add a call to moveByRotorSpeed either in  c++ example files and how to build it the example?  Your comments will be deeply appreciated.

After I checked the python examples, it seems the call is not yet implemented as it does not exist in AirSimClient.py file. 

Thanks!

**Comment by zbenic** [comment]
Hello.

Can you checkout this commit from my pull request:
https://github.com/Microsoft/AirSim/pull/890

In there, in the commit 5ca1d920343042e95faefc2c94bede2b73b13c51 you can find the help for my function in the DroneShell/src/main.cpp, line 452.

Also, implementation to the AirSimClient.py can be found in the commit 741f98363950b65e3058606061538378ae112df6.

I don't remember having any problems building it or doing anything out of the ordinary to build it.

**Comment by juanmed** [comment]
Hello! Thanks so much for your reply. I did noticed the first commit before but missed the second one. Thanks so much for your time and reply! I will try to reimplement in the current release of Airsim.

I also did not have any issues with building your MultirotorRL repository. The building was smooth. The only issue I am having now trying to run the examples is the following error message. I am not completely sure what does it mean but looking at the issues in Airsim main repository, it seems something related to Unreal. 

I want to at least replicate your results so that I can proceed to implement them myself. Today I will try installing unreal and your MultirotorRL repo in a fresh Ubuntu install to see if I can replicate your results. 

`Waiting for connection: Traceback (most recent call last):
  File "hello_drone.py", line 15, in <module>
    client.confirmConnection()
  File "/home/fer/git_clone2/zbenic_MultirotorRL/MultirotorRL/PythonClient/AirSimClient.py", line 210, in confirmConnection
    home = self.getHomeGeoPoint()
  File "/home/fer/git_clone2/zbenic_MultirotorRL/MultirotorRL/PythonClient/AirSimClient.py", line 219, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))
  File "/usr/local/lib/python3.5/dist-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/usr/local/lib/python3.5/dist-packages/msgpackrpc/future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'getHomeGeoPoint' was called with an invalid number of arguments. Expected: 0, got: 1`

**Comment by juanmed** [comment]
Actually the error was that I was running the Blocks Environment of the lastest Airsim release instead of the one from your repository. After loading and compiling the Blocks Env from your repo, the hello_drone.py script runs. Now I will try to add the changes in your second commit since they dont appear to be in your MultirotorRL repo.

**Comment by juanmed** [comment]
Hey hello. I just wanted to update you that I was able to run your repo and changes and actually move the drone using your moveByRotorSpeed functions. Thanks for your help.

I also wanted to ask if it is ok to cite your repo in my issue in Airsim github. Since I want to continue working based on your work, I want to document the changes I make in that issue. This implies mentioning your work. However I understand this might generated undesired traffic to this repository, since you are not working in this anymore.

**Comment by zbenic** [comment]
Hello.

You are welcome.

I have no problems with you citing my repo. Also, I'm interested in your future progress on this matter, so I will follow your progress.
